osx_image: xcode7.3
dist: trusty
sudo: false
language: c
matrix:
  include:
  - os: osx
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- export CHROME_BIN=chromium-browser
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.5.5/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.5.5.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
install:
- nvm install 8
- npm install --force
- npm add jquery
- npm add popper.js
script:
- npm rebuild node-sass
- npm run build
- npm run package-mac
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "AiKOiIkvrZiEj/QiamgtyCnWdHBJPDTp88yQyKCKfqvhK3P1fkH12uAF/Ml7ySv0rfh9amf1OA/FsCsSLo0fIt3dOrUY/e2TdJj9g5v5H3tNq9/2GPCFJHol5gwzejrjEYbXtggzjKsYiJo1sYUVafC1sPDcAI7Db/0z1EvRJ0mnMtcBJg+B6gabrjJnf62oo/RnPYnvLsqacNOQe7c3NcNid748ma7a2ClwgZNuEY2kq9lgvo50/k/tCm/QxBtamwz8fbS2MpwwBHzXthA9p5e7Xv0Y5Oey9nU/LpCrPw6RW6wEkHustss+lAWYmYOu9NLosXWnkUpVbY9fD3FaiM4iU2RVSAFEB4Xu3LGMn9NDlO2uIe+V4mHppXlGxLdzoEFqUT+VG86PEfwYF0A0hVzH68xwShCcN9kS7aRgHAmE/caXDPoGaVfyxJ3W9VmlkvrI8ErI8vMtvkkj9+545+mMNbgVynMH+5tpe68JYVA9EHxgVtApQ11FM8Rsl9IBGIfHhDtuH9p3AQm2KPmTWHgcD/sigiSXoD+7ZtRLrdfUI9kZ9fcI+0x3H7lZzDAzxvAEnjMOyyxJzMdxtcNv2m5B0N7Wz02PbpD0zHr2suKIu12/WHKEU5zjAbwzKfmuBAuTtiDDy72hk1404azQeDUvgTc9Jc23z4xlhPy7kwY="
  file_glob: true
  file: release/*.dmg
  on:
    tags: true
    all_branches: true
    repo: scuy/idai-field
notifications:
  slack:
    on_success: never
    on_failure: always
    secure: Rr7TV3RjR3NROqHObnoRY3kUx2iLIuczrIt8J2+Lfvh50Bu0qSSlsKoY8bOuxUQQ2bK7e98qJPBFUL3L8n49E/vwJxGYRaEQEb0YvJz/hfHjKOR1CiFiw7pc30iATMI98ElQS7c9sBw0jx/gkPpJIxksx2gO1Xwofze38E5pPtlzxh5y8CY6qD4UoPxodT1mTAXO8JBn3k947CVU/pXS7I5byc5Uc4k9PHYM7PLGXpGHHst3DiUjQfhD4OmHDQFQxwueBhlQCkLP7a47fHJIuthNNxOqocFofOIAhRPS4vjVVk5ePxUbIItQ/htcKAzQ/AI0Fv8SLA3V4TfTjdVcyzPXAM0Tty6iN6Fqhn8+E3yrmDNqPM99vtofDrNwEAUHoPN2qZSVTSz3bjJ5FW5ywtc0L+vLo6j5FAmgeKnz3aLbMzztcd65ouXnfGm75Gu5cRxyLNs8oIuwjOuFgk1497u7lwsOF8Ocw0EinJzJkuSaHjwEbKg11iBoyu5FrhNodU00GagoSuDXxwXPZu1kO8xgWsjbDxR0Fe421n6uOf2y4Es1r/9eWLwLbqbqSL8WseFNa2BV21UYpNM1tUkUMayHb9EmO73Wg9NiT8vQN4yVl7oyTK7Ynyo06Wb6u+xv/aXocXb1C42UiX35K4g5Cvx3RCYHBaOrprczmSE0I5Y=
