osx_image: xcode7.3
dist: trusty
sudo: false
language: c
matrix:
  include:
  - os: osx
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- export CHROME_BIN=chromium-browser
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.5.5/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.5.5.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
install:
- nvm install 8
- npm install --force
- npm add jquery
- npm add popper.js
script:
- npm rebuild node-sass
- npm run build
- npm run package-mac
notifications:
  slack:
    on_success: never
    on_failure: always
    secure: Rr7TV3RjR3NROqHObnoRY3kUx2iLIuczrIt8J2+Lfvh50Bu0qSSlsKoY8bOuxUQQ2bK7e98qJPBFUL3L8n49E/vwJxGYRaEQEb0YvJz/hfHjKOR1CiFiw7pc30iATMI98ElQS7c9sBw0jx/gkPpJIxksx2gO1Xwofze38E5pPtlzxh5y8CY6qD4UoPxodT1mTAXO8JBn3k947CVU/pXS7I5byc5Uc4k9PHYM7PLGXpGHHst3DiUjQfhD4OmHDQFQxwueBhlQCkLP7a47fHJIuthNNxOqocFofOIAhRPS4vjVVk5ePxUbIItQ/htcKAzQ/AI0Fv8SLA3V4TfTjdVcyzPXAM0Tty6iN6Fqhn8+E3yrmDNqPM99vtofDrNwEAUHoPN2qZSVTSz3bjJ5FW5ywtc0L+vLo6j5FAmgeKnz3aLbMzztcd65ouXnfGm75Gu5cRxyLNs8oIuwjOuFgk1497u7lwsOF8Ocw0EinJzJkuSaHjwEbKg11iBoyu5FrhNodU00GagoSuDXxwXPZu1kO8xgWsjbDxR0Fe421n6uOf2y4Es1r/9eWLwLbqbqSL8WseFNa2BV21UYpNM1tUkUMayHb9EmO73Wg9NiT8vQN4yVl7oyTK7Ynyo06Wb6u+xv/aXocXb1C42UiX35K4g5Cvx3RCYHBaOrprczmSE0I5Y=
